openapi: 3.0.0
info:
  title: Bookshelf API
  version: 1.0.0
servers:
  - url: http://localhost:8086
tags:
  - name: Book
  - name: Bookshelf
  - name: User
  - name: Bookshelf Entry
paths:
  /api/books:
    post:
      tags:
        - Book
      summary: Add a single Book

      requestBody:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  book:
                    type: object
                    example:
                      $ref: '#/components/schemas/Book'
      responses:

components:
  schemas:
    User:
      type: object
      properties:
        uuid:
          type: string
          example: "009BVWKVgHb0ERn3edblbJgAXwI2"
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
    Book:
      type: object
      properties:
        title:
          type: string
          example: Osmosis (Osmose)

        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'

        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'

        publisher:
          type: string
          example: Thoughtbridge

        dateOfPublication:
          type: string
          example: 08-03-2019

        isbn:
          type: string
          example: 168923674-4
    Bookshelf Entry:
        type: object
        properties:
          readingStatus:
            type: integer
            example: 0, 1 or 2 - (0 = not done, 1 = reading, 2 = done)
          onWishlist:
            type: boolean
          book:
            type: object
            example:
              $ref: '#/components/schemas/Book'
    Author:
      type: string
      example: Evania Rollett
    Genre:
      type: string
      example: "Comedy"
    Publisher:
      type: string
      example: Thoughtbridge