openapi: 3.0.0
info:
  title: Bookshelf API
  description: Bookshelf Api - Save, modify or delete your bookshelf entries in a database
  version: 1.0.0
servers:
  - url: http://localhost:8086
tags:
  - name: Book
  - name: Bookshelf
  - name: Users
paths:
  /api/users/books:
    get:
      tags:
        - Users
      summary: Get a list of all users and their bookshelf entries
      responses:
        200:
          description: Returns a user uuid and their books in a list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /api/users/add:
      post:
        tags:
          - Users
        summary: Adds a new user
        description: New user is created along with a bookshelf entry list
        requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    uuid:
                      type: string
                      example: '009BVWKVgHb0ERn3edblbJgAXwI2'
        responses:
          201:
            description: Created
            content:
              text/plain:
                schema:
                  type: string
                  example: 'User with uuid: 009BVWKVgHb0ERn3edblbJgAXwI2 was registered.'

  /api/bookshelf/{id}/add:
    post:
      tags:
        - Bookshelf
      summary: Add new book to a users bookshelf
      parameters:
        - name: id
          in: path
          description: Uuid of a user
          required: true
          schema:
            type: integer
      requestBody:
          description: Takes a book object
          content:
            application/json:
              schema:
                type: object
                properties:
                  book:
                    $ref: '#/components/schemas/Book'
      responses:
        201:
          description: Created
          content:
            text/plain:
              schema:
                type: string
                example: 'The Book Osmosis (Osmose)(isbn: 168923674-4) was added to the bookshelf of: TzOF19jkvPUzEg5rWtrSHQ49Esg2.'
components:
  schemas:
    User:
      type: object
      description: Represents a user and
      properties:
        uuid:
          type: string
          example: '009BVWKVgHb0ERn3edblbJgAXwI2'
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
    Book:
      type: object
      properties:
        title:
          type: string
          example: Osmosis (Osmose)

        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'

        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'

        publisher:
          type: string
          example: Thoughtbridge

        dateOfPublication:
          type: string
          example: 08-03-2019

        isbn:
          type: string
          example: 168923674-4
    Bookshelf Entry:
        type: object
        properties:
          readingStatus:
            type: integer
            example: 0, 1 or 2 - (0 = not done, 1 = reading, 2 = done)
          onWishlist:
            type: boolean
          book:
            type: object
            example:
              $ref: '#/components/schemas/Book'
    Author:
      type: string
      example: Evania Rollett
    Genre:
      type: string
      example: 'Comedy'
    Publisher:
      type: string
      example: Thoughtbridge